### PR TITLE
Task3

### PR DESCRIPTION
**Pull request by Harshal662**
Changed Class plugin

### CODE REVIEW

**Review by txoof — CHANGES_REQUESTED** [review]
The checks look reasonable, but probably belong in the decorated .setter methods rather than in __init__.

If they're in the setters, the checks will always be done even when set outside of __init__. It's unlikely that this will be the case, but I'd rather keep it tidy to future proof this.

**Comment by Harshal662** [comment]
plz check

**Review by txoof — COMMENTED** [review]
These look perfect. It's great that they all either throw TypeError or ValueError; that will make catching them elsewhere easier.

Would you be able to merge these into the `.ipynb` files instead of the python? 

The workflow for the development is to do most of the work in the notebooks, then generate the .py files from the notebooks.

**Comment by Harshal662** [comment]
okay. Should I close this pr and create a new pr where only .ipynb file is edited

**Pull request closed without merging**
